# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dan Nolan
email: dan.nolan28@gmail.com
description: Hello! I'm Dan Nolan. I'm an interactive designer and graphic designer working in Boston.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: d_jnol
github_username:  djnolan
exclude: [about.md, contact.md]
sass:
  style: compressed

collections:
  projects:
    output: true

# Build settings
markdown: kramdown
excerpt_separator: <!--description-->


